name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            farhan100799/skripsi-fe:latest
            farhan100799/skripsi-fe:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker rm -f skripsi-fe
            docker pull farhan100799/skripsi-fe:latest
            docker run -p 3002:3000 -d --name skripsi-fe farhan100799/skripsi-fe
            docker rmi $(docker images -q --filter "dangling=true")
